#!/usr/bin/env node
// Regenerates docs/product-context.md from the codebase.
//
// The point is a single file that describes what this product actually is —
// accurate enough to hand to a model, a new contributor, or a compliance
// reviewer without anyone first re-reading the source. Everything below is
// derived from the repository rather than written by hand, so it cannot drift:
// when a screen or a function is added, this file changes with it, and CI fails
// if the committed copy no longer matches what the code says.
//
//   npm run context          regenerate
//   npm run context:check    fail if the committed copy is stale (used in CI)

import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(path.join(root, p), "utf8");
const dirs = (p) => (existsSync(path.join(root, p)) ? readdirSync(path.join(root, p), { withFileTypes: true }) : []);

/** First `//` comment block above the handler, as one line — the author's own
 *  summary. Imports and blank lines are skipped, since these files open with
 *  them and the describing comment sits underneath. */
function leadingComment(source) {
  const lines = [];
  for (const line of source.split("\n")) {
    const t = line.trim();
    if (t.startsWith("//")) lines.push(t.replace(/^\/\/\s?/, ""));
    else if (lines.length > 0) break;                 // block ended
    else if (t === "" || t.startsWith("import ")) continue;
    else break;                                       // real code before any comment
  }
  // Keep it to the first sentence; the rest is implementation detail.
  const text = lines.join(" ").replace(/\s+/g, " ").trim();
  const stop = text.search(/\.\s/);
  return stop === -1 ? text : text.slice(0, stop + 1);
}

function screens() {
  return dirs("src/pages")
    .filter((f) => f.name.endsWith(".jsx"))
    .map((f) => f.name.replace(/\.jsx$/, ""))
    .sort();
}

function serverFunctions() {
  return dirs("supabase/functions")
    .filter((d) => d.isDirectory() && !d.name.startsWith("_"))
    .map((d) => {
      const entry = path.join("supabase/functions", d.name, "index.ts");
      const summary = existsSync(path.join(root, entry)) ? leadingComment(read(entry)) : "";
      return { name: d.name, summary };
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** Top-level keys of the object computeStats() returns — the analytics vocabulary. */
function metrics() {
  const src = read("src/lib/analytics.js");
  const start = src.indexOf("\n  return {");
  if (start === -1) return [];
  const body = src.slice(start, src.indexOf("\n  };", start));
  const keys = [...body.matchAll(/^\s{4}([a-zA-Z][\w]*)[,:]/gm)].map((m) => m[1]);
  return [...new Set(keys)];
}

function schema() {
  const files = dirs("supabase/migrations").filter((f) => f.name.endsWith(".sql")).map((f) => f.name).sort();
  const tables = new Map();
  for (const file of files) {
    const sql = read(path.join("supabase/migrations", file));
    for (const m of sql.matchAll(/create table (?:if not exists )?public\.(\w+)\s*\(([\s\S]*?)\n\);/g)) {
      const cols = m[2]
        .split("\n")
        .map((l) => l.trim())
        .filter((l) => l && !/^(primary key|unique|check|constraint|foreign key)/i.test(l))
        .map((l) => l.split(/\s+/)[0])
        .filter((c) => /^\w+$/.test(c));
      tables.set(m[1], new Set(cols));
    }
    for (const m of sql.matchAll(/alter table (?:only )?public\.(\w+)[\s\S]*?add column (?:if not exists )?(\w+)/g)) {
      if (tables.has(m[1])) tables.get(m[1]).add(m[2]);
    }
  }
  return [...tables].map(([name, cols]) => ({ name, cols: [...cols] }));
}

/** The `###` headings of docs/deferred-work.md — what is knowingly not built. */
function deferred() {
  if (!existsSync(path.join(root, "docs/deferred-work.md"))) return [];
  return [...read("docs/deferred-work.md").matchAll(/^### (.+)$/gm)].map((m) => m[1].trim());
}

function recentWork() {
  try {
    return execSync('git log -15 --format="%ad  %s" --date=short', { cwd: root }).toString().trim().split("\n");
  } catch {
    return [];
  }
}

const out = `<!-- GENERATED by scripts/product-context.mjs — do not edit by hand.
     Run \`npm run context\` after changing screens, functions, schema or analytics. -->

# DeltaMint — product context

A single current description of this product, generated from the codebase. Give
this to a model, a new contributor, or a reviewer instead of explaining the
product from memory.

## What it is

DeltaMint is a browser tool for self-directed options traders who run
defined-risk multi-leg positions — credit spreads and iron condors. It holds no
customer funds or securities, executes nothing itself, and gives no advice.
Users link their own brokerage account; every order is placed at their
direction, through that account.

Its distinguishing job is **portfolio comprehension**: brokers list option legs
individually, so one iron condor appears as four unrelated rows. DeltaMint pairs
legs back into the structure that created them and reports each position's real
credit, risk, break-evens and value. That matters more the more positions a
trader holds, which is the constraint the product exists to lift.

Revenue is a flat monthly subscription. No commission, no share of profits,
nothing contingent on trading activity.

## Architecture

- **Frontend** — Vite + React single-page app, static assets on Cloudflare Workers.
- **Backend** — Supabase: Postgres with row-level security, Auth, and Deno edge functions.
- **Broker access** — every brokerage API call happens in an edge function, never the browser.
- **Marketing site** — separate static Cloudflare Worker (\`landing/\`).

## Screens

${screens().map((s) => `- ${s}`).join("\n")}

## Server functions

Each runs as its own bundle carrying a copy of what it imports from \`_shared/\`,
so a change to shared code requires redeploying all of them.

${serverFunctions().map((f) => `- **${f.name}** — ${f.summary || "(no summary comment)"}`).join("\n")}

## Database

Row-level security scopes every table to \`auth.uid()\`. Brokerage credentials are
encrypted with AES-256-GCM before storage, with the key held in the edge
function environment rather than the database, and the credential columns are
revoked from the browser role entirely.

${schema().map((t) => `- **${t.name}** — ${t.cols.join(", ")}`).join("\n")}

## Analytics vocabulary

Computed by \`src/lib/analytics.js\` from reconstructed closed trades. Notable for
being premium-seller specific rather than generic profit and loss: credit
capture is the kept share of premium sold, and return on risk is measured
against peak *concurrent* collateral rather than the sum of every trade.

${metrics().map((m) => `\`${m}\``).join(" · ")}

## Known gaps

Deliberately not built yet — see \`docs/deferred-work.md\`.

${deferred().map((d) => `- ${d}`).join("\n") || "- (none recorded)"}

## Recent work

${recentWork().map((l) => `- ${l}`).join("\n")}
`;

const target = path.join(root, "docs/product-context.md");

if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current.trim() !== out.trim()) {
    console.error("docs/product-context.md is out of date. Run `npm run context` and commit the result.");
    process.exit(1);
  }
  console.log("docs/product-context.md is current.");
} else {
  writeFileSync(target, out);
  console.log("Wrote docs/product-context.md");
}
